---
abstract: 'optional scripts for hubot'
author:
  - 'Hyungsuk Hong <hshong@perl.kr>'
  - 'Hojung Youn <amoc.yn@gmail.com>'
build_requires:
  AnyEvent: 0
  Hubot::Adapter: 0
  Hubot::Message: 0
  Hubot::Robot: 0
  Hubot::User: 0
  Moose: 0
  Test::More: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hubot-Scripts-Bundle
requires:
  AnyEvent::HTTP::ScopedClient: 0
  DateTime: 0
  DateTime::Format::Duration: 0
  Encode: 0
  JSON::XS: 0
  Lingua::KO::Hangul::Util: 0
  Redis: 0
  Try::Tiny: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.1.0
